//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CRMModel", "IDUsuario2", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mobileCRM.Models.Usuario), "Tarefas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mobileCRM.Models.Tarefa), true)]
[assembly: EdmRelationshipAttribute("CRMModel", "IDUsuario_Visitas", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mobileCRM.Models.Usuario), "Visitas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mobileCRM.Models.Visita), true)]

#endregion

namespace mobileCRM.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CRMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CRMEntities object using the connection string found in the 'CRMEntities' section of the application configuration file.
        /// </summary>
        public CRMEntities() : base("name=CRMEntities", "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRMEntities object.
        /// </summary>
        public CRMEntities(string connectionString) : base(connectionString, "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRMEntities object.
        /// </summary>
        public CRMEntities(EntityConnection connection) : base(connection, "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tarefa> Tarefas
        {
            get
            {
                if ((_Tarefas == null))
                {
                    _Tarefas = base.CreateObjectSet<Tarefa>("Tarefas");
                }
                return _Tarefas;
            }
        }
        private ObjectSet<Tarefa> _Tarefas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Visita> Visitas
        {
            get
            {
                if ((_Visitas == null))
                {
                    _Visitas = base.CreateObjectSet<Visita>("Visitas");
                }
                return _Visitas;
            }
        }
        private ObjectSet<Visita> _Visitas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tarefas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarefas(Tarefa tarefa)
        {
            base.AddObject("Tarefas", tarefa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Visitas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitas(Visita visita)
        {
            base.AddObject("Visitas", visita);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Tarefa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tarefa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tarefa object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        public static Tarefa CreateTarefa(global::System.Int32 handle, global::System.Int32 iDUsuario)
        {
            Tarefa tarefa = new Tarefa();
            tarefa.Handle = handle;
            tarefa.IDUsuario = iDUsuario;
            return tarefa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Assunto
        {
            get
            {
                return _Assunto;
            }
            set
            {
                OnAssuntoChanging(value);
                ReportPropertyChanging("Assunto");
                _Assunto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Assunto");
                OnAssuntoChanged();
            }
        }
        private global::System.String _Assunto;
        partial void OnAssuntoChanging(global::System.String value);
        partial void OnAssuntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInicio;
        partial void OnDataInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataConclusao
        {
            get
            {
                return _DataConclusao;
            }
            set
            {
                OnDataConclusaoChanging(value);
                ReportPropertyChanging("DataConclusao");
                _DataConclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataConclusao");
                OnDataConclusaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataConclusao;
        partial void OnDataConclusaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataConclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataAgendada
        {
            get
            {
                return _DataAgendada;
            }
            set
            {
                OnDataAgendadaChanging(value);
                ReportPropertyChanging("DataAgendada");
                _DataAgendada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAgendada");
                OnDataAgendadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataAgendada;
        partial void OnDataAgendadaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataAgendadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataLembrete
        {
            get
            {
                return _DataLembrete;
            }
            set
            {
                OnDataLembreteChanging(value);
                ReportPropertyChanging("DataLembrete");
                _DataLembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataLembrete");
                OnDataLembreteChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataLembrete;
        partial void OnDataLembreteChanging(Nullable<global::System.DateTime> value);
        partial void OnDataLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lembrete
        {
            get
            {
                return _Lembrete;
            }
            set
            {
                OnLembreteChanging(value);
                ReportPropertyChanging("Lembrete");
                _Lembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lembrete");
                OnLembreteChanged();
            }
        }
        private Nullable<global::System.Int32> _Lembrete;
        partial void OnLembreteChanging(Nullable<global::System.Int32> value);
        partial void OnLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AgendarTarefa
        {
            get
            {
                return _AgendarTarefa;
            }
            set
            {
                OnAgendarTarefaChanging(value);
                ReportPropertyChanging("AgendarTarefa");
                _AgendarTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgendarTarefa");
                OnAgendarTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _AgendarTarefa;
        partial void OnAgendarTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnAgendarTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario2", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 handle, global::System.String nome, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.Handle = handle;
            usuario.Nome = nome;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario2", "Tarefas")]
        public EntityCollection<Tarefa> Tarefas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarefa>("CRMModel.IDUsuario2", "Tarefas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarefa>("CRMModel.IDUsuario2", "Tarefas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario_Visitas", "Visitas")]
        public EntityCollection<Visita> Visitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Visita>("CRMModel.IDUsuario_Visitas", "Visitas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Visita>("CRMModel.IDUsuario_Visitas", "Visitas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Visita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visita : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Visita object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        public static Visita CreateVisita(global::System.Int32 handle, global::System.Int32 iDUsuario)
        {
            Visita visita = new Visita();
            visita.Handle = handle;
            visita.IDUsuario = iDUsuario;
            return visita;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Assunto
        {
            get
            {
                return _Assunto;
            }
            set
            {
                OnAssuntoChanging(value);
                ReportPropertyChanging("Assunto");
                _Assunto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Assunto");
                OnAssuntoChanged();
            }
        }
        private global::System.String _Assunto;
        partial void OnAssuntoChanging(global::System.String value);
        partial void OnAssuntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInicio;
        partial void OnDataInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataConclusao
        {
            get
            {
                return _DataConclusao;
            }
            set
            {
                OnDataConclusaoChanging(value);
                ReportPropertyChanging("DataConclusao");
                _DataConclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataConclusao");
                OnDataConclusaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataConclusao;
        partial void OnDataConclusaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataConclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataAgendada
        {
            get
            {
                return _DataAgendada;
            }
            set
            {
                OnDataAgendadaChanging(value);
                ReportPropertyChanging("DataAgendada");
                _DataAgendada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAgendada");
                OnDataAgendadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataAgendada;
        partial void OnDataAgendadaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataAgendadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lembrete
        {
            get
            {
                return _Lembrete;
            }
            set
            {
                OnLembreteChanging(value);
                ReportPropertyChanging("Lembrete");
                _Lembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lembrete");
                OnLembreteChanged();
            }
        }
        private Nullable<global::System.Int32> _Lembrete;
        partial void OnLembreteChanging(Nullable<global::System.Int32> value);
        partial void OnLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AgendarTarefa
        {
            get
            {
                return _AgendarTarefa;
            }
            set
            {
                OnAgendarTarefaChanging(value);
                ReportPropertyChanging("AgendarTarefa");
                _AgendarTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgendarTarefa");
                OnAgendarTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _AgendarTarefa;
        partial void OnAgendarTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnAgendarTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClienteBase
        {
            get
            {
                return _ClienteBase;
            }
            set
            {
                OnClienteBaseChanging(value);
                ReportPropertyChanging("ClienteBase");
                _ClienteBase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClienteBase");
                OnClienteBaseChanged();
            }
        }
        private Nullable<global::System.Int32> _ClienteBase;
        partial void OnClienteBaseChanging(Nullable<global::System.Int32> value);
        partial void OnClienteBaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoTarefa
        {
            get
            {
                return _TipoTarefa;
            }
            set
            {
                OnTipoTarefaChanging(value);
                ReportPropertyChanging("TipoTarefa");
                _TipoTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoTarefa");
                OnTipoTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoTarefa;
        partial void OnTipoTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnTipoTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario_Visitas", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
