//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CRMModel", "IDUsuario2", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mobileCRM.Models.Usuario), "Tarefas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mobileCRM.Models.Tarefa), true)]
[assembly: EdmRelationshipAttribute("CRMModel", "IDUsuario_Visitas", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mobileCRM.Models.Usuario), "Visitas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mobileCRM.Models.Visita), true)]
[assembly: EdmRelationshipAttribute("CRMModel", "IDCliente_Visitas", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mobileCRM.Models.Clientes), "Visita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mobileCRM.Models.Visita), true)]

#endregion

namespace mobileCRM.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CRMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CRMEntities object using the connection string found in the 'CRMEntities' section of the application configuration file.
        /// </summary>
        public CRMEntities() : base("name=CRMEntities", "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRMEntities object.
        /// </summary>
        public CRMEntities(string connectionString) : base(connectionString, "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CRMEntities object.
        /// </summary>
        public CRMEntities(EntityConnection connection) : base(connection, "CRMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tarefa> Tarefas
        {
            get
            {
                if ((_Tarefas == null))
                {
                    _Tarefas = base.CreateObjectSet<Tarefa>("Tarefas");
                }
                return _Tarefas;
            }
        }
        private ObjectSet<Tarefa> _Tarefas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Visita> Visitas
        {
            get
            {
                if ((_Visitas == null))
                {
                    _Visitas = base.CreateObjectSet<Visita>("Visitas");
                }
                return _Visitas;
            }
        }
        private ObjectSet<Visita> _Visitas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clientes> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Clientes>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Clientes> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Event> Event
        {
            get
            {
                if ((_Event == null))
                {
                    _Event = base.CreateObjectSet<Event>("Event");
                }
                return _Event;
            }
        }
        private ObjectSet<Event> _Event;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tarefas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTarefas(Tarefa tarefa)
        {
            base.AddObject("Tarefas", tarefa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Visitas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitas(Visita visita)
        {
            base.AddObject("Visitas", visita);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Clientes clientes)
        {
            base.AddObject("Clientes", clientes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Event EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvent(Event @event)
        {
            base.AddObject("Event", @event);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Clientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clientes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clientes object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="cargo">Initial value of the Cargo property.</param>
        /// <param name="empresa">Initial value of the Empresa property.</param>
        /// <param name="ramoAtividade">Initial value of the RamoAtividade property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        public static Clientes CreateClientes(global::System.Int32 handle, global::System.String nome, global::System.Int32 cargo, global::System.String empresa, global::System.Int32 ramoAtividade, global::System.String telefone)
        {
            Clientes clientes = new Clientes();
            clientes.Handle = handle;
            clientes.Nome = nome;
            clientes.Cargo = cargo;
            clientes.Empresa = empresa;
            clientes.RamoAtividade = ramoAtividade;
            clientes.Telefone = telefone;
            return clientes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cargo
        {
            get
            {
                return _Cargo;
            }
            set
            {
                OnCargoChanging(value);
                ReportPropertyChanging("Cargo");
                _Cargo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cargo");
                OnCargoChanged();
            }
        }
        private global::System.Int32 _Cargo;
        partial void OnCargoChanging(global::System.Int32 value);
        partial void OnCargoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Empresa
        {
            get
            {
                return _Empresa;
            }
            set
            {
                OnEmpresaChanging(value);
                ReportPropertyChanging("Empresa");
                _Empresa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Empresa");
                OnEmpresaChanged();
            }
        }
        private global::System.String _Empresa;
        partial void OnEmpresaChanging(global::System.String value);
        partial void OnEmpresaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RamoAtividade
        {
            get
            {
                return _RamoAtividade;
            }
            set
            {
                OnRamoAtividadeChanging(value);
                ReportPropertyChanging("RamoAtividade");
                _RamoAtividade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RamoAtividade");
                OnRamoAtividadeChanged();
            }
        }
        private global::System.Int32 _RamoAtividade;
        partial void OnRamoAtividadeChanging(global::System.Int32 value);
        partial void OnRamoAtividadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Site
        {
            get
            {
                return _Site;
            }
            set
            {
                OnSiteChanging(value);
                ReportPropertyChanging("Site");
                _Site = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Site");
                OnSiteChanged();
            }
        }
        private global::System.String _Site;
        partial void OnSiteChanging(global::System.String value);
        partial void OnSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NivelInteresse
        {
            get
            {
                return _NivelInteresse;
            }
            set
            {
                OnNivelInteresseChanging(value);
                ReportPropertyChanging("NivelInteresse");
                _NivelInteresse = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NivelInteresse");
                OnNivelInteresseChanged();
            }
        }
        private Nullable<global::System.Int32> _NivelInteresse;
        partial void OnNivelInteresseChanging(Nullable<global::System.Int32> value);
        partial void OnNivelInteresseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CEP
        {
            get
            {
                return _CEP;
            }
            set
            {
                OnCEPChanging(value);
                ReportPropertyChanging("CEP");
                _CEP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CEP");
                OnCEPChanged();
            }
        }
        private global::System.String _CEP;
        partial void OnCEPChanging(global::System.String value);
        partial void OnCEPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoLogradouro
        {
            get
            {
                return _TipoLogradouro;
            }
            set
            {
                OnTipoLogradouroChanging(value);
                ReportPropertyChanging("TipoLogradouro");
                _TipoLogradouro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoLogradouro");
                OnTipoLogradouroChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoLogradouro;
        partial void OnTipoLogradouroChanging(Nullable<global::System.Int32> value);
        partial void OnTipoLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private Nullable<global::System.Int32> _Numero;
        partial void OnNumeroChanging(Nullable<global::System.Int32> value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UF
        {
            get
            {
                return _UF;
            }
            set
            {
                OnUFChanging(value);
                ReportPropertyChanging("UF");
                _UF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UF");
                OnUFChanged();
            }
        }
        private global::System.String _UF;
        partial void OnUFChanging(global::System.String value);
        partial void OnUFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrigemContato
        {
            get
            {
                return _OrigemContato;
            }
            set
            {
                OnOrigemContatoChanging(value);
                ReportPropertyChanging("OrigemContato");
                _OrigemContato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OrigemContato");
                OnOrigemContatoChanged();
            }
        }
        private Nullable<global::System.Int32> _OrigemContato;
        partial void OnOrigemContatoChanging(Nullable<global::System.Int32> value);
        partial void OnOrigemContatoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Potencial
        {
            get
            {
                return _Potencial;
            }
            set
            {
                OnPotencialChanging(value);
                ReportPropertyChanging("Potencial");
                _Potencial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Potencial");
                OnPotencialChanged();
            }
        }
        private Nullable<global::System.Int32> _Potencial;
        partial void OnPotencialChanging(Nullable<global::System.Int32> value);
        partial void OnPotencialChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDCliente_Visitas", "Visita")]
        public EntityCollection<Visita> Visitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Visita>("CRMModel.IDCliente_Visitas", "Visita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Visita>("CRMModel.IDCliente_Visitas", "Visita", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Event object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="text">Initial value of the text property.</param>
        /// <param name="eventstart">Initial value of the eventstart property.</param>
        /// <param name="eventend">Initial value of the eventend property.</param>
        public static Event CreateEvent(global::System.Int32 id, global::System.String text, global::System.DateTime eventstart, global::System.DateTime eventend)
        {
            Event @event = new Event();
            @event.id = id;
            @event.text = text;
            @event.eventstart = eventstart;
            @event.eventend = eventend;
            return @event;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime eventstart
        {
            get
            {
                return _eventstart;
            }
            set
            {
                OneventstartChanging(value);
                ReportPropertyChanging("eventstart");
                _eventstart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventstart");
                OneventstartChanged();
            }
        }
        private global::System.DateTime _eventstart;
        partial void OneventstartChanging(global::System.DateTime value);
        partial void OneventstartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime eventend
        {
            get
            {
                return _eventend;
            }
            set
            {
                OneventendChanging(value);
                ReportPropertyChanging("eventend");
                _eventend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eventend");
                OneventendChanged();
            }
        }
        private global::System.DateTime _eventend;
        partial void OneventendChanging(global::System.DateTime value);
        partial void OneventendChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Tarefa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tarefa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tarefa object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        public static Tarefa CreateTarefa(global::System.Int32 handle, global::System.Int32 iDUsuario)
        {
            Tarefa tarefa = new Tarefa();
            tarefa.Handle = handle;
            tarefa.IDUsuario = iDUsuario;
            return tarefa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Assunto
        {
            get
            {
                return _Assunto;
            }
            set
            {
                OnAssuntoChanging(value);
                ReportPropertyChanging("Assunto");
                _Assunto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Assunto");
                OnAssuntoChanged();
            }
        }
        private global::System.String _Assunto;
        partial void OnAssuntoChanging(global::System.String value);
        partial void OnAssuntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInicio;
        partial void OnDataInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataConclusao
        {
            get
            {
                return _DataConclusao;
            }
            set
            {
                OnDataConclusaoChanging(value);
                ReportPropertyChanging("DataConclusao");
                _DataConclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataConclusao");
                OnDataConclusaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataConclusao;
        partial void OnDataConclusaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataConclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataAgendada
        {
            get
            {
                return _DataAgendada;
            }
            set
            {
                OnDataAgendadaChanging(value);
                ReportPropertyChanging("DataAgendada");
                _DataAgendada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAgendada");
                OnDataAgendadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataAgendada;
        partial void OnDataAgendadaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataAgendadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataLembrete
        {
            get
            {
                return _DataLembrete;
            }
            set
            {
                OnDataLembreteChanging(value);
                ReportPropertyChanging("DataLembrete");
                _DataLembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataLembrete");
                OnDataLembreteChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataLembrete;
        partial void OnDataLembreteChanging(Nullable<global::System.DateTime> value);
        partial void OnDataLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lembrete
        {
            get
            {
                return _Lembrete;
            }
            set
            {
                OnLembreteChanging(value);
                ReportPropertyChanging("Lembrete");
                _Lembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lembrete");
                OnLembreteChanged();
            }
        }
        private Nullable<global::System.Int32> _Lembrete;
        partial void OnLembreteChanging(Nullable<global::System.Int32> value);
        partial void OnLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AgendarTarefa
        {
            get
            {
                return _AgendarTarefa;
            }
            set
            {
                OnAgendarTarefaChanging(value);
                ReportPropertyChanging("AgendarTarefa");
                _AgendarTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgendarTarefa");
                OnAgendarTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _AgendarTarefa;
        partial void OnAgendarTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnAgendarTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario2", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CRMModel.IDUsuario2", "Usuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 handle, global::System.String nome, global::System.String senha)
        {
            Usuario usuario = new Usuario();
            usuario.Handle = handle;
            usuario.Nome = nome;
            usuario.Senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario2", "Tarefas")]
        public EntityCollection<Tarefa> Tarefas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tarefa>("CRMModel.IDUsuario2", "Tarefas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tarefa>("CRMModel.IDUsuario2", "Tarefas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario_Visitas", "Visitas")]
        public EntityCollection<Visita> Visitas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Visita>("CRMModel.IDUsuario_Visitas", "Visitas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Visita>("CRMModel.IDUsuario_Visitas", "Visitas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CRMModel", Name="Visita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visita : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Visita object.
        /// </summary>
        /// <param name="handle">Initial value of the Handle property.</param>
        /// <param name="iDUsuario">Initial value of the IDUsuario property.</param>
        /// <param name="iDCliente">Initial value of the IDCliente property.</param>
        public static Visita CreateVisita(global::System.Int32 handle, global::System.Int32 iDUsuario, global::System.Int32 iDCliente)
        {
            Visita visita = new Visita();
            visita.Handle = handle;
            visita.IDUsuario = iDUsuario;
            visita.IDCliente = iDCliente;
            return visita;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Handle
        {
            get
            {
                return _Handle;
            }
            set
            {
                if (_Handle != value)
                {
                    OnHandleChanging(value);
                    ReportPropertyChanging("Handle");
                    _Handle = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Handle");
                    OnHandleChanged();
                }
            }
        }
        private global::System.Int32 _Handle;
        partial void OnHandleChanging(global::System.Int32 value);
        partial void OnHandleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Assunto
        {
            get
            {
                return _Assunto;
            }
            set
            {
                OnAssuntoChanging(value);
                ReportPropertyChanging("Assunto");
                _Assunto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Assunto");
                OnAssuntoChanged();
            }
        }
        private global::System.String _Assunto;
        partial void OnAssuntoChanging(global::System.String value);
        partial void OnAssuntoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataInicio
        {
            get
            {
                return _DataInicio;
            }
            set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataInicio;
        partial void OnDataInicioChanging(Nullable<global::System.DateTime> value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataConclusao
        {
            get
            {
                return _DataConclusao;
            }
            set
            {
                OnDataConclusaoChanging(value);
                ReportPropertyChanging("DataConclusao");
                _DataConclusao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataConclusao");
                OnDataConclusaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataConclusao;
        partial void OnDataConclusaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataConclusaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataAgendada
        {
            get
            {
                return _DataAgendada;
            }
            set
            {
                OnDataAgendadaChanging(value);
                ReportPropertyChanging("DataAgendada");
                _DataAgendada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataAgendada");
                OnDataAgendadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataAgendada;
        partial void OnDataAgendadaChanging(Nullable<global::System.DateTime> value);
        partial void OnDataAgendadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lembrete
        {
            get
            {
                return _Lembrete;
            }
            set
            {
                OnLembreteChanging(value);
                ReportPropertyChanging("Lembrete");
                _Lembrete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lembrete");
                OnLembreteChanged();
            }
        }
        private Nullable<global::System.Int32> _Lembrete;
        partial void OnLembreteChanging(Nullable<global::System.Int32> value);
        partial void OnLembreteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AgendarTarefa
        {
            get
            {
                return _AgendarTarefa;
            }
            set
            {
                OnAgendarTarefaChanging(value);
                ReportPropertyChanging("AgendarTarefa");
                _AgendarTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AgendarTarefa");
                OnAgendarTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _AgendarTarefa;
        partial void OnAgendarTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnAgendarTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClienteBase
        {
            get
            {
                return _ClienteBase;
            }
            set
            {
                OnClienteBaseChanging(value);
                ReportPropertyChanging("ClienteBase");
                _ClienteBase = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClienteBase");
                OnClienteBaseChanged();
            }
        }
        private Nullable<global::System.Int32> _ClienteBase;
        partial void OnClienteBaseChanging(Nullable<global::System.Int32> value);
        partial void OnClienteBaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoTarefa
        {
            get
            {
                return _TipoTarefa;
            }
            set
            {
                OnTipoTarefaChanging(value);
                ReportPropertyChanging("TipoTarefa");
                _TipoTarefa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoTarefa");
                OnTipoTarefaChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoTarefa;
        partial void OnTipoTarefaChanging(Nullable<global::System.Int32> value);
        partial void OnTipoTarefaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUsuario
        {
            get
            {
                return _IDUsuario;
            }
            set
            {
                OnIDUsuarioChanging(value);
                ReportPropertyChanging("IDUsuario");
                _IDUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDUsuario");
                OnIDUsuarioChanged();
            }
        }
        private global::System.Int32 _IDUsuario;
        partial void OnIDUsuarioChanging(global::System.Int32 value);
        partial void OnIDUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDCliente
        {
            get
            {
                return _IDCliente;
            }
            set
            {
                OnIDClienteChanging(value);
                ReportPropertyChanging("IDCliente");
                _IDCliente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDCliente");
                OnIDClienteChanged();
            }
        }
        private global::System.Int32 _IDCliente;
        partial void OnIDClienteChanging(global::System.Int32 value);
        partial void OnIDClienteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDUsuario_Visitas", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("CRMModel.IDUsuario_Visitas", "Usuarios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CRMModel", "IDCliente_Visitas", "Clientes")]
        public Clientes Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("CRMModel.IDCliente_Visitas", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("CRMModel.IDCliente_Visitas", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clientes> ClientesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clientes>("CRMModel.IDCliente_Visitas", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clientes>("CRMModel.IDCliente_Visitas", "Clientes", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
